# Generated by Django 3.1 on 2022-08-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20220820_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='user',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
