# Generated by Django 3.1 on 2022-08-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20220820_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
