# Generated by Django 3.1 on 2022-08-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20220820_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='end_date',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='start_date',
            new_name='last',
        ),
    ]
