# Generated by Django 3.1 on 2022-08-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20220821_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhotels',
            name='hoteladdress',
        ),
    ]
