# Generated by Django 3.1 on 2022-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_remove_myhotels_hoteladdress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
